language: python
sudo: false

os:
  - linux

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

matrix:
  allow_failures:
      - python: "nightly"

install:
  - sudo apt-get -qq update
  - sudo apt-get -y install pandoc
  - pandoc --from=markdown --to=rst --output=README.rst README.md
  - pip install codecov
  - pip install -e .

script:
  - python -V
  - coverage run tests.py

after_success:
  - codecov
